app:
  autoscale:
    enabled: true
  redirectFrom:
    - "nos1000jours-web-pro.fabrique.social.gouv.fr"

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "47"
          NEXT_PUBLIC_MATOMO_ENABLED: "true"
          NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
          NEXT_PUBLIC_API_URL: https://backoffice-les1000jours.fabrique.social.gouv.fr
